# Generated by Django 3.0.1 on 2020-01-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200105_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='profile_default.png', upload_to='profile'),
        ),
        migrations.AddField(
            model_name='executer',
            name='image',
            field=models.ImageField(default='profile_default.png', upload_to='profile'),
        ),
    ]
