# Generated by Django 3.0.1 on 2020-01-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200109_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='executer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
