# Generated by Django 3.0.1 on 2020-01-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200109_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executer',
            old_name='description',
            new_name='profession',
        ),
    ]
