# Generated by Django 3.0.1 on 2020-01-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200109_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='default/profile_default.png', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='executer',
            name='image',
            field=models.ImageField(default='default/profile_default.png', upload_to='profile'),
        ),
    ]
