# Generated by Django 3.0.1 on 2020-01-03 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('orders', '0002_order_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('condition', models.BooleanField(default=False)),
                ('executer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses_orders', to='profiles.Executer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_orders', to='orders.Order')),
            ],
        ),
    ]
