# Generated by Django 3.0.1 on 2020-01-04 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('orders', '0003_responseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseorder',
            name='executer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='responses_orders', to='profiles.Executer'),
            preserve_default=False,
        ),
    ]
