# Generated by Django 3.0.1 on 2020-01-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200109_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, default='default/order_default.png', upload_to='orders'),
        ),
    ]
